# Generated by Django 5.0.1 on 2024-08-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
    ]
